### ISSUE TITLE
Support ability to add additional config when initiate driver

### ISSUE THREAD

**Issue by stormit-vn** [LucianoPAlmeida/OGMNeo#14]
Is that possible to allow specify config parameter when initiating driver instance likes below code sample

const driver = neo4j.driver(url, neo4j.auth.basic(user, pwd), {
    encrypted: false
});

Thanks

**Comment by LucianoPAlmeida** [comment]
Hey @stormit-vn, it isn't possible yet but I can add this to the next version. Comming soon :)

**Comment by LucianoPAlmeida** [comment]
Hey @stormit-vn, v1.0.2 just released with this option on Connection.connect() :)

**Comment by stormit-vn** [comment]
That is perfect. Thanks
