### ISSUE TITLE
merge nodes and relations

### ISSUE THREAD

**Issue by peterclemenko** [LucianoPAlmeida/OGMNeo#15]
Having a merge function for nodes and relationships would help for carrying out creating unique nodes/relations.

**Comment by LucianoPAlmeida** [comment]
Hey @aoighost 
Awesome, thank you for your suggestion :) 
That can be a useful feature. I will take a look and see how we can implement this and give you a feedback as soon as possible. But feel free to propose an API definition for a merge function or submit a PR with a proposal that we can work on together :))

**Comment by peterclemenko** [comment]
I've written up a prototype but haven't tested it yet. All I did was change the create stuffto merge. I'll PR it and we can figure out what to do from there.

**Comment by LucianoPAlmeida** [comment]
@aoighost That's awesome, I'll take a look as soon possible :))

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucianoPAlmeida** [comment]
@aoighost I've merge #16 and done some fixes on #20 👍 
Thank's for implementing this functionality 💯
