### ISSUE TITLE
Node with all relation

### ISSUE THREAD

**Issue by usama-ayub** [LucianoPAlmeida/OGMNeo#21]
how to fetch node and these relations.

**Comment by LucianoPAlmeida** [comment]
Hey, really sorry for the late answer 😅 
But if someone is also having this question [here](http://ogmneo-docs.getforge.io/OGMNeoRelationQuery.html) is the docs.
Also some examples on the [tests](https://github.com/LucianoPAlmeida/OGMNeo/blob/b2b0e843fd24fd92deda8b611489b33d8f4d10e7/__test__/relation-tests.js#L215)
