### ISSUE TITLE
Too many "ECONNRESET" error

### ISSUE THREAD

**Issue by stormit-vn** [LucianoPAlmeida/OGMNeo#23]
We are getting a lot of "ECONNRESET" errors. So I wanted to create this issue so that we can get someone can help. I am not sure whether this is neo4j itself or this ORM library. 

Neo4jError: read ECONNRESET\n\n at captureStacktrace (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/result.js:200:15)\n at new Result (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/result.js:73:19)\n at _newRunResult (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/transaction.js:348:10)\n at Object.run (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/transaction.js:259:14)\n at Transaction.run (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/transaction.js:103:26)\n at Function.runInTransaction (/var/neo4j-sample-app/node_modules/ogmneo/lib/ogmneo-operation-executer.js:154:32)\n at session.readTransaction (/var/neo4j-sample-app/node_modules/ogmneo/lib/ogmneo-operation-executer.js:129:40)\n at TransactionExecutor._executeTransactionInsidePromise (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:115:37)\n at /var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:67:15\n at new Promise ()\n at new F (/var/neo4j-sample-app/node_modules/core-js/library/modules/_export.js:36:28)\n at TransactionExecutor.execute (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:66:14)\n at Session._runTransaction (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/session.js:214:40)\n at Session.readTransaction (/var/neo4j-sample-app/node_modules/neo4j-driver/lib/v1/session.js:187:19)\n at Promise (/var/neo4j-sample-app/node_modules/ogmneo/lib/ogmneo-operation-executer.js:128:25)\n at new Promise ()\n at Function._executeRead (/var/neo4j-sample-app/node_modules/ogmneo/lib/ogmneo-operation-executer.js:122:16)\n at Function.execute (/var/neo4j-sample-app/node_modules/ogmneo/lib/ogmneo-operation-executer.js:110:29)\n at OGMNeoModel.findOne (/var/neo4j-sample-app/src/api/ogm-neo/ogmneo-model.js:399:44)\n at OAuthAccessTokenManager.findOne (/var/neo4j-sample-app/src/api/managers/BaseManager.js:242:27)\n at onJwtBearerStrategyAuth (/var/neo4j-sample-app/src/config/passport.js:102:52)\n at /var/neo4j-sample-app/node_modules/passport-http-jwt-bearer/lib/strategy.js:99:11

This is running on the environment below:
NodeJS v8.9.3
Neo4J v3.4.0
neo4j-driver v1.6.2
The app is running on a Docker container with Centos 7

There are some issues have been raised in the neo4j driver but we still not figure out the root cause and resolution
https://github.com/philippkueng/node-neo4j/issues/43
https://github.com/neo4j/neo4j-javascript-driver/issues/126

**Comment by LucianoPAlmeida** [comment]
Hey @stormit-vn :)) 
I'll take a look on that as soon as possible 👍

**Comment by stormit-vn** [comment]
@LucianoPAlmeida Luc thank you for your attention. I have added some configurations and seems this issue is no longer occurring. See my comments from the references issues for more details

**Comment by LucianoPAlmeida** [comment]
I see 👍 Seems like a config parameter then
Thanks for the feedback :))
