### ISSUE TITLE
docs not hosted

### ISSUE THREAD

**Issue by bionicles** [LucianoPAlmeida/OGMNeo#6]
Hi, the docs link just goes to a folder of HTML files, is it possible to host that for free somehow?

**Comment by LucianoPAlmeida** [comment]
Hi @bionicles, thank's for the idea, i'll work on that an make it happen as soon as possible :)

**Comment by LucianoPAlmeida** [comment]
@bionicles Done 👍 
The docs are now hosted on http://ogmneo-docs.getforge.io/
