### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by sunzd116** [LucianoPAlmeida/OGMNeo#7]
hello,
I use OGMNeo in koa server, But I got an socket error like this:

![error](https://user-images.githubusercontent.com/9314683/28204161-63232fe4-68af-11e7-8aa1-7c0f6cc4852e.png)

i cannot catch this error in `koa middleWare`
i catch it in `process.on`

**Comment by sunzd116** [comment]
so i want to kown when you release your socket connection,
did you meet this error before?

**Comment by LucianoPAlmeida** [comment]
Hey @sunzd116 i already meet this error before, but it was my node aplication that was already running on the port 3000. So i had to use the lsof -i tpc:3000 to find the PID of the process running on that port and kill it. But i'm no sure if its the same error.

I close the connection on 
```` js
     process.on('exit', () => { OGMNeo.disconnect(); });
````

**Comment by sunzd116** [comment]
thank you :)

**Comment by sunzd116** [comment]
i got it . it is because the ldap client did not release the socket connection, OGMNeo is  really good :)
