### ISSUE TITLE
cannot find execute function in ogmneo.Cypher

### ISSUE THREAD

**Issue by sunzd116** [LucianoPAlmeida/OGMNeo#8]
I cannot find execute function in ogmneo.Cypher.
when did you update it?

**Comment by sunzd116** [comment]
please add this function to ogmneo.Cypher again  :-)

**Comment by LucianoPAlmeida** [comment]
Hey @sunzd116, it just have been separated and renamed to [ogmneo.Cypher.transactionalRead](http://ogmneo-docs.getforge.io/OGMNeoCypher) and [ogmneo.Cypher.transactionalWrite](http://ogmneo-docs.getforge.io/OGMNeoCypher), sorry my mistake i should had deprecated it first before removing.
